---
- hosts: mariadb 
  gather_facts: no
  become: yes
  become_method: sudo
  vars: 
    wp_hosts: "192.168.145.145"
  roles:
   - mariadb
  
- hosts: wordpress
  gather_facts: no
  become: yes
  become_method: sudo 
  vars: 
    db_hosts: "192.168.145.145"
  roles:
   - wordpress
...
