---
- hosts: mariadb 
  gather_facts: yes
  become: yes
  become_user: root
# become_method: sudo
  roles:
   - mariadb
  
- hosts: wordpress
  gather_facts: yes
  become: yes
  become_user: root
# become_method: sudo 
  roles:
   - wordpress
...
