---
- hosts: wordpress
  gather_facts: no
  become: yes
  become_method: sudo 
  roles:
   - wordpress

- hosts: mariadb 
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
   - mariadb
...
